In [1]:
import pandas as pd
import os
import numpy as np
import zipcode
import haversine
pd.set_option('display.max_columns', 50)

In [2]:
#return files from given path and all its subdirectories to the lowest level
def ReturnDataFiles(path):
    print("checking path :-",path)
    filesInPath=[]
    for f in os.listdir(path):
        if os.path.isdir(os.path.join(path,f)):
           dataFiles=ReturnDataFiles(os.path.join(path,f))
           for file in dataFiles:
                filesInPath.append(file)
        else :
            if(os.path.isfile(os.path.join(path,f))):
                filesInPath.append(os.path.join(path,f))
    print("files found at ", path, ":-",filesInPath)
    return filesInPath

In [3]:
#read files from path and load
def MergeAndLoadFile(path='datasets\List'):
    print (os.listdir('datasets\List'))
    dirPath='datasets\List'
    files = [f for f in os.listdir(dirPath) if os.path.isfile(os.path.join(dirPath,f))]
    print(files)
    merged = []

    for f in files:
        filePath=os.path.join(dirPath,f)
        filename, ext = os.path.splitext(filePath)
        print('ext')
        if ext == '.csv':
            print('found csv')
            try:
                read = pd.read_csv(filePath,error_bad_lines=False,sep=';')
                merged.append(read)
            except:
                print('error for :- ',filePath)
    result = pd.concat(merged)
   
    result.to_csv('merged.csv')

In [4]:
#merge files from list given
def MergeAndLoadFile(files):
    
    
   
  
    merged = []

    for f in files:
       
        filename, ext = os.path.splitext(f)
        print('ext')
        if ext == '.csv':
            print('found csv')
            try:
                print("reading ",f)
                read = pd.read_csv(f,error_bad_lines=False,sep=';')
                merged.append(read)
            except:
                print('error for :- ',f)
        if ext =='.xls':
            try:
                read = pd.read_excel(f,error_bad_lines=False)
                merged.append(read)
            except:
                print('error for :- ',f)
    result = pd.concat(merged)
   
    result.to_csv('mergedsample.csv')

In [5]:
#sample reading of an .xls file
import xlrd
filePath=os.path.join("Samples","M_201702_521.xls")
read = pd.read_excel(filePath,error_bad_lines=False)
read.head()

,Store,Primary Store,Card Number,Last Name,First Name,Middle Initial,Address 1,Address 2,City,State,Zip,Zip + 4,Phone,DOB,Sales in 201702,Trips,Sales per Trip,Points in 201702,Current Available Points,Primary Language,Opt Out,Email
0,521,521,6006500491003809792,DIAZ,ANGEL,NaN,414 PALISADE AVE,NaN,YONKERS,NY,10703,2611.0,9.144269e+09,19000101,69.96,3.0,23.32,0.0,0,Spanish,NaN,NaN
1,521,521,6005411420005359616,DOS SANTOS,MARIA,D,57 HIGH ST APT 2,NaN,YONKERS,NY,10703,3210.0,9.144232e+09,19350611,681.26,17.0,40.07,0.0,0,Spanish,NaN,NaN
2,521,521,6005411420015240192,LAMAR,TENIKA,S,354 NEPPERHAM AVE,NaN,YONKERS,NY,10701,4427.0,9.149433e+09,19000101,40.32,2.0,20.16,0.0,0,English,NaN,NaN
3,521,521,6005411420005369856,LAMBERTO,GERALDINE,NaN,90 GATEWAY RD APT 181S,NaN,YONKERS,NY,10703,1282.0,9.143781e+09,19490123,128.08,6.0,21.35,0.0,0,English,NaN,gerriny@msn.com
4,521,521,6005411420005380096,PHILLIP,VIRGINIA,B,50 VAN CORTLANDT PK AVE # A,NaN,YONKERS,NY,10701,7616.0,9.143789e+09,19000101,37.26,4.0,9.31,0.0,0,English,NaN,NaN

In [6]:
files=ReturnDataFiles("Samples")
print(files)

checking path :- Samples
files found at  Samples :- ['Samples\\mergedsample.csv', 'Samples\\M_201702_521.xls', 'Samples\\M_201802_521.csv']
['Samples\\mergedsample.csv', 'Samples\\M_201702_521.xls', 'Samples\\M_201802_521.csv']

In [7]:
print(len(files))

3

In [8]:
MergeAndLoadFile(files)

ext
found csv
reading  Samples\mergedsample.csv
ext
ext
found csv
reading  Samples\M_201802_521.csv

In [9]:
localPath=os.path.join("Samples")
fileName=os.path.join(localPath,"mergedsample.csv")
csvFile= pd.read_csv(fileName,error_bad_lines=False,sep=',')

In [10]:
#assign a dummy zip code
csvFile["Store Zip"]='07733'

In [11]:
csvFile["Sales in 201702"].fillna(0, inplace=True)
csvFile["Sales in 201802"].fillna(0, inplace=True)

csvFile["Sales"]= csvFile["Sales in 201702"]+csvFile["Sales in 201802"]
csvFile["Points"]= csvFile["Points in 201702"]+csvFile["Points in 201802"]

In [12]:

csvFile.drop(columns=["Sales in 201702","Sales in 201802","Points in 201702","Points in 201802"])

,Unnamed: 0,Address 1,Address 2,Card Number,City,Current Available Points,DOB,Email,First Name,Last Name,Middle Initial,Opt Out,Phone,Primary Language,Primary Store,Sales per Trip,State,Store,Trips,Zip,Zip + 4,Store Zip,Sales,Points
0,0,414 PALISADE AVE,NaN,6006500491003809792,YONKERS,0,19000101,NaN,ANGEL,DIAZ,NaN,NaN,9144269244.0,Spanish,521,23.32,NY,521,3.0,10703,2611.0,07733,69.96,NaN
1,1,57 HIGH ST APT 2,NaN,6005411420005359616,YONKERS,0,19350611,NaN,MARIA,DOS SANTOS,D,NaN,9144232181.0,Spanish,521,40.07,NY,521,17.0,10703,3210.0,07733,681.26,NaN
2,2,354 NEPPERHAM AVE,NaN,6005411420015240192,YONKERS,0,19000101,NaN,TENIKA,LAMAR,S,NaN,9149433451.0,English,521,20.16,NY,521,2.0,10701,4427.0,07733,40.32,NaN
3,3,90 GATEWAY RD APT 181S,NaN,6005411420005369856,YONKERS,0,19490123,gerriny@msn.com,GERALDINE,LAMBERTO,NaN,NaN,9143781304.0,English,521,21.35,NY,521,6.0,10703,1282.0,07733,128.08,NaN
4,4,50 VAN CORTLANDT PK AVE # A,NaN,6005411420005380096,YONKERS,0,19000101,NaN,VIRGINIA,PHILLIP,B,NaN,9143788605.0,English,521,9.31,NY,521,4.0,10701,7616.0,07733,37.26,NaN
5,5,130 ELM ST APT 2W,NaN,6005411420025169920,YONKERS,0,19000101,NaN,GLENDA,SUAZO,NaN,NaN,9143769324.0,English,521,23.62,NY,521,5.0,10701,8098.0,07733,118.09,NaN
6,6,550 PALISADE AVE FL 3,NaN,6005411420005399552,YONKERS,0,19000101,NaN,CARMEN,MONTALVO,NaN,NaN,9142601562.0,Spanish,521,19.20,NY,521,8.0,10703,2108.0,07733,153.60,NaN
7,7,304 MCLEAN AVE APT 2,NaN,6005411420005420032,YONKERS,0,19000101,NaN,THERESIA,GEBIEN,NaN,NaN,9144765706.0,English,521,28.07,NY,521,3.0,10705,4489.0,07733,84.22,NaN
8,8,300 N BROADWAY APT 4E,NaN,6005411420001089536,YONKERS,0,19000101,NaN,MICHELLE,RIVAS,NaN,NaN,9144577561.0,English,521,11.26,NY,521,1.0,10701,2688.0,07733,11.26,NaN
9,9,7 PAUL PL,NaN,6005411420001089536,PALM COAST,0,19000101,NaN,ALEJANDRI,ROSARIO,NaN,NaN,0.0,Spanish,521,12.19,FL,521,3.0,32164,7538.0,07733,36.58,NaN
10,10,47 LEROY AVE # 1,NaN,6005411420015250432,YONKERS,0,19461116,NaN,RAMONA,SAUNDERS,NaN,NaN,9144232254.0,English,521,11.18,NY,521,5.0,10705,4519.0,07733,55.90,NaN
11,11,54 FAIRVIEW ST APT 1F,NaN,6005411420010200064,YONKERS,0,19510707,NaN,JULIE,SANTIAGO,NaN,NaN,9147517218.0,English,521,8.32,NY,521,4.0,10703,3044.0,07733,33.29,NaN
12,12,17 MULBERRY ST # 2R,NaN,6005411420028839936,YONKERS,0,19000101,NaN,FATIMA,ROSARIO,NaN,NaN,9149686108.0,English,521,18.79,NY,521,6.0,10701,6087.0,07733,112.71,NaN
13,13,131 PARK AVE BSMT,NaN,6005411420010210304,YONKERS,0,19591201,NaN,EDDA,FIGUEROA,NaN,NaN,9143762496.0,Spanish,521,22.65,NY,521,1.0,10703,2996.0,07733,22.65,NaN
14,14,287 PALISADE AVE APT 2G,NaN,6005411420025159680,YONKERS,0,19700922,NaN,MARIA,SOTO,NaN,NaN,9143190950.0,Spanish,521,229.20,NY,521,1.0,10703,2911.0,07733,229.20,NaN
15,15,19 EASTVIEW AVE 1FL,NaN,6005411420011219968,YONKERS,0,19710613,anava.rmd@gmail.com,ANTONIA,NAVA,NaN,NaN,9149685962.0,English,521,92.77,NY,521,1.0,10703,2292.0,07733,92.77,NaN
16,16,234 SUMMERVILLE,NaN,6005411420011219968,YONKERS,0,19400803,NaN,LUZ,CRUZ,NaN,NaN,9143761374.0,English,521,18.36,NY,521,1.0,10703,NaN,07733,18.36,NaN
17,17,632 VAN CORTLANDT PARK AVE,NaN,6005411420009060352,YONKERS,0,19000101,NaN,LEAH,BURRELL,P,NaN,9146304940.0,English,521,20.60,NY,521,1.0,10705,4251.0,07733,20.60,NaN
18,18,455 N BROADWAY APT 8,NaN,6005411420015259648,YONKERS,0,19751128,tiona75@yahoo.com,TIONA,GUNTHORPE,NaN,NaN,9143257535.0,English,521,11.34,NY,521,2.0,10701,1950.0,07733,22.67,NaN
19,19,247 SOMMERVILLE PL # 2,NaN,6005411420013559808,YONKERS,0,19630803,NaN,MARIO,MALDONADO,A,NaN,9143789178.0,English,521,32.42,NY,521,1.0,10703,2210.0,07733,32.42,NaN
20,20,2 FR FINNIAN SULIVAN AP 11L,NaN,6005411420013559808,YONKERS,0,19431025,NaN,MARGARITA,MAYORGA,NaN,NaN,9143752270.0,English,521,5.00,NY,521,1.0,10705,4352.0,07733,5.00,NaN
21,21,377 N BROADWAY APT 619,NaN,6005411420014390272,YONKERS,0,19630324,NaN,ANITA,MINCEY,NaN,NaN,9149686450.0,English,521,12.57,NY,521,1.0,10701,2021.0,07733,12.57,NaN
22,22,89 ELM ST APT 3E,NaN,6005411420402929664,YONKERS,0,19000101,NaN,ADELA,HERNANDEZ,NaN,NaN,9142075538.0,Spanish,521,26.55,NY,521,13.0,10701,3960.0,07733,345.19,NaN
23,23,218 74TH ST,NaN,6005411420011950080,BROOKLYN,0,19000101,NaN,FELICIA,CABRERA,NaN,NaN,7187452066.0,English,521,32.41,NY,521,1.0,11209,2410.0,07733,32.41,NaN
24,24,380 N BROADWAY,NaN,6005411420010420224,YONKERS,0,19000101,NaN,GLADYS,ADDO DANSO,NaN,NaN,9149692487.0,English,521,2.58,NY,521,2.0,10701,2059.0,07733,5.17,NaN
25,25,86 DICKENS ST,NaN,6005411420017729536,WOODMERE,165,19000101,NaN,DARRYL,GREENSTEIN,NaN,NaN,5163747969.0,English,521,2.99,NY,521,1.0,11598,NaN,07733,2.99,NaN
26,26,222 N BROADWAY,NaN,6005411420011480064,YONKERS,0,19000101,NaN,SHEILA,POLANCO,NaN,NaN,9149697020.0,English,521,8.88,NY,521,4.0,10701,2606.0,07733,35.51,NaN
27,27,116 OAK ST APT 3,NaN,6005411420029930496,YONKERS,0,19720228,NaN,CARLINE,CLARKE,NaN,NaN,9146198309.0,English,521,16.11,NY,521,1.0,10701,4327.0,07733,16.11,NaN
28,28,2964 BRIGGS AVE,NaN,6005411420020209664,BRONX,7035,19800407,NaN,LIZETTE ADRESS APT#,COLON PLEASE UPDATE,NaN,NaN,9178257810.0,English,521,11.34,NY,521,1.0,10458,2001.0,07733,11.34,NaN
29,29,3400 TRYON AVE,NaN,6005411420020219904,BRONX,0,19740822,NaN,MARIELA,VASQUEZ,NaN,NaN,7182316082.0,English,521,11.64,NY,521,5.0,10467,2524.0,07733,58.21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6213,2838,N,,6005411420410170993,YONKERS,0,19000101,,ANTONIO,FERNANDEZ,,NaN,9144972839,English,562,18.43,NY,521,1.0,10704,,07733,18.43,NaN
6214,2839,,,6005411420416771448,YONKERS,0,19000101,,IRYNA,BODNARCHAK,,NaN,9143762049,English,562,15.38,NY,521,3.0,10703,,07733,46.15,NaN
6215,2840,286 MORSEMERE AVE # 2,,6005411420039552753,YONKERS,0,19640823,,VINICIO,SANCHEZ,,NaN,9142070493,English,575,10.78,NY,521,1.0,10703,2220,07733,10.78,NaN
6216,2841,1912 NEREID AVE,,6005411420045194400,BRONX,0,19000101,,ROZENA,NAZIR,,NaN,7189941143,English,575,16.66,NY,521,2.0,10466,1226,07733,33.31,NaN
6217,2842,9 CHATHAM TERRACE,,6005411420045592827,YONKERS,0,19761022,,MICHELLE,MARR,,NaN,9175772625,English,575,27.32,NY,521,1.0,10710,,07733,27.32,NaN
6218,2843,7 LAKE AVE,,6005411420040636678,YONKERS,0,19000101,,DONA,GRANT,,NaN,3474458230,English,575,13.22,NY,521,3.0,10703,2604,07733,39.66,NaN
6219,2844,4305 FURMAN AVE,4D,6005411420410871301,BRONX,0,19630804,,DIANA,SANCHEZ,Y,NaN,3474839891,English,575,30.91,NY,521,4.0,10466,,07733,123.65,NaN
6220,2845,3215 BAINBRIDGE AVE APT 54,,6005411420415005954,BRONX,21755,19000101,,MANUEL,GONZALEZ,,NaN,9175694574,English,582,40.61,NY,521,1.0,10467,3981,07733,40.61,NaN
6221,2846,3291 HULL AVE BSMT,,6005411420405757689,BRONX,3082,19791122,,PATRICK,HANNIGAN,A,NaN,7185191458,English,582,48.62,NY,521,1.0,10467,3344,07733,48.62,NaN
6222,2847,300 PALISADE AVE,,6005411420048508408,YONKERS,5906,19000101,,ANDRE,SANTIAGO,,NaN,9144193205,English,582,11.15,NY,521,2.0,10703,3115,07733,22.31,NaN
6223,2848,,,6005411420048501239,YONKERS,7856,19000101,,NO,NAME,,NaN,9140000000,English,582,7.98,NY,521,1.0,10703,,07733,7.98,NaN
6224,2849,1001 JEROME AVE APT 11A,,6006500410030435850,BRONX,35521,19390625,,LAURA,MCLURKIN,L,NaN,7185882734,English,585,11.09,NY,521,1.0,10452,5767,07733,11.09,NaN
6225,2850,98 CONVENT PL,,6005411420040637114,YONKERS,1295,19000101,,EILEEN,LOGIODICE,,NaN,9144236554,English,598,20.60,NY,521,2.0,10703,2510,07733,41.20,NaN
6226,2851,,,6005411420386078477,NaN,17117,19000101,,E,BASSITT,,NaN,9148675309,English,606,31.95,NY,521,1.0,10573,,07733,31.95,NaN
6227,2852,,,6005411420046672818,YONKERS,3954,19000101,,SAMANTHA,GIBBONS,,NaN,9146736006,English,606,6.97,NY,521,1.0,10703,,07733,6.97,NaN
6228,2853,PO BOX 871,,6005411420414772455,ELMSFORD,9217,19740719,MAINTAINYOURCOMPOSURE@GMAIL.COM,KEITH,HARMON,M,NaN,9146431552,English,606,52.40,NY,521,1.0,10523,,07733,52.40,NaN
6229,2854,393 EDGECOMBE AVE APT 33,,6005411420044136105,NEW YORK,1825,19590309,,MAXIMINA,FERNANDEZ,,NaN,2124917195,English,609,7.98,NY,521,1.0,10031,1334,07733,7.98,NaN
6230,2855,259 WEST 109TH STREET,APT.3W,6005411420413003522,NEW YORK,5446,19000101,,KENYA,DAVIS,,NaN,3474334625,English,609,17.92,NY,521,1.0,10025,,07733,17.92,NaN
6231,2856,,,6005411420411103274,NEW YORK,34832,19570606,,MATTHEW,MINGO,,NaN,3474883007,English,609,18.84,NY,521,2.0,10039,,07733,37.67,NaN
6232,2857,226 WEST,,6005411420411220730,NY,14903,19000101,,WILEMINE,BENOIT,,NaN,2122815681,English,609,12.67,NY,521,1.0,10039,,07733,12.67,NaN
6233,2858,78-10 34TH AVE,APT#3C,6005411420401283607,JACKSON HEIGHTS,0,19670110,CCBALES@HOTMAIL.COM,CHARLES,BALES,C,NaN,7183874257,English,622,32.76,NY,521,1.0,11372,,07733,32.76,NaN
6234,2859,,3449 CORSA AVENUE,6005411420020626012,MOUNT VERNON,0,19000101,,ADA,STEPHENS,,NaN,9173929235,English,646,28.75,NY,521,2.0,10469,,07733,57.49,NaN
6235,2860,755 WHITE PLAINS RD,,6005411420045527245,BRONX,0,19761121,,FOSTER,DODGE,,NaN,3476793391,English,646,1.49,NY,521,1.0,10473,2635,07733,1.49,NaN
6236,2861,,,6005411420040651370,YONKERS,0,19000101,,FRANCISCO,SOMAR,,NaN,3472342196,English,646,11.87,NY,521,1.0,10703,,07733,11.87,NaN
6237,2862,,,6005411420412656882,BX,0,19000101,,PATRICIA,TITTLE,,NaN,3475495640,English,646,5.20,NY,521,2.0,10469,,07733,10.40,NaN
6238,2863,151 RIDGE AVE APT 2R,,6005411420400951055,YONKERS,0,19000101,,NADIA,CHIN,,NaN,3477015877,English,646,26.20,NY,521,1.0,10710,,07733,26.20,NaN
6239,2864,9 WHELON PLACE,,6005411420400915217,YONKERS,0,19000101,,DOMICA,WALSH,,NaN,7187756311,English,647,15.76,NY,521,1.0,10703,,07733,15.76,NaN
6240,2865,96 JANET DR APT-D,,6005411420413785656,POUGHKEEPSIE,0,19000101,,TINA,POWELL,,NaN,9147743297,English,671,6.53,NY,521,1.0,12601,,07733,6.53,NaN
6241,2866,220 YONKERS AVE APT 11J,,6005411420029934557,YONKERS,0,19000101,,MARYANN,WATKINS,,NaN,9149683065,English,692,16.16,NY,521,1.0,10701,6223,07733,16.16,NaN
6242,2867,57 MORNING SIDE PL,,6005411420048499905,YONKERS,0,19000101,,EBONY,SCOTT,,NaN,9143127873,English,701,7.64,NY,521,2.0,10703,,07733,15.28,NaN

In [13]:
#Convert Zip and store Zip to string
csvFile['Zip']= csvFile['Zip'].astype(str)
csvFile['Store Zip']= csvFile['Store Zip'].astype(str)

In [14]:
#check how many Zips are ' '
csvFile.loc[csvFile['Zip']==' ']
csvFile['Zip'].value_counts() #816

10703              3670
10701              1577
                    176
nan                 152
10705               132
10550                52
10463                40
10704                39
10710                28
10467                20
0                    19
10702                13
10469                13
10466                12
10552                11
10461                 8
10708                 8
10553                 8
10458                 8
10032                 6
10462                 6
10460                 6
10465                 6
1                     6
UNKNOW                6
00000                 6
10573                 6
10031                 5
10707                 5
10452                 5
                   ...
10607                 1
107019149635470       1
000000                1
11598                 1
16607                 1
10322                 1
10001                 1
13788                 1
11364                 1
1703                  1
420416769177          1
11238                 1
12804                 1
10920                 1
107033                1
10601                 1
10793                 1
11361                 1
10571                 1
107201                1
10474                 1
10451                 1
30088                 1
15498                 1
10173                 1
10043                 1
10524                 1
0703                  1
10801                 1
11358                 1
Name: Zip, Length: 143, dtype: int64

In [15]:
csvFile = csvFile.applymap(lambda x: np.nan if (isinstance(x, str) and x.isspace())or(x=='nan') else x)

csvFile['Zip'].value_counts(dropna=False)

10703              3670
10701              1577
NaN                 328
10705               132
10550                52
10463                40
10704                39
10710                28
10467                20
0                    19
10702                13
10469                13
10466                12
10552                11
10553                 8
10461                 8
10708                 8
10458                 8
10032                 6
10460                 6
10462                 6
00000                 6
1                     6
10465                 6
10573                 6
UNKNOW                6
10707                 5
10031                 5
10452                 5
10025                 4
                   ...
10533                 1
11598                 1
701                   1
2                     1
08750                 1
107036                1
10607                 1
107019149635470       1
10801                 1
0703                  1
10524                 1
10043                 1
1703                  1
11238                 1
10322                 1
12804                 1
10920                 1
107033                1
10601                 1
10793                 1
11361                 1
10571                 1
000000                1
107201                1
10451                 1
16607                 1
30088                 1
15498                 1
10173                 1
11236                 1
Name: Zip, Length: 142, dtype: int64

In [16]:



csvFile.dropna(subset=['Zip','Store Zip'],inplace=True,how='any')
csvFile['Zip'].value_counts(dropna=False)

10703              3670
10701              1577
10705               132
10550                52
10463                40
10704                39
10710                28
10467                20
0                    19
10702                13
10469                13
10466                12
10552                11
10458                 8
10461                 8
10553                 8
10708                 8
00000                 6
10462                 6
UNKNOW                6
1                     6
10460                 6
10573                 6
10465                 6
10032                 6
10031                 5
10452                 5
10707                 5
10706                 4
10470                 4
                   ...
107036                1
10607                 1
107019149635470       1
000000                1
11598                 1
16607                 1
10322                 1
10001                 1
13788                 1
10548                 1
11364                 1
10474                 1
12804                 1
10920                 1
107033                1
10601                 1
10793                 1
11361                 1
10571                 1
420416769177          1
107201                1
10451                 1
30088                 1
15498                 1
10173                 1
10043                 1
10524                 1
0703                  1
10801                 1
11358                 1
Name: Zip, Length: 141, dtype: int64

In [17]:
csvFile.loc[csvFile['Zip']=='NaN']
invalidZipCount=0

In [18]:
print(invalidZipCount)

0

In [19]:
def distanceFromStore(row):
    try:
        global invalidZipCount
        
        storeZip= row['Store Zip']


        userZip= row['Zip']
        
        userZipObject= zipcode.isequal(userZip)
      
    
        storeZipObject= zipcode.isequal(storeZip)

        

        storeAddress=(storeZipObject.lat,storeZipObject.lon)

        userAddress= (userZipObject.lat,userZipObject.lon)

        distance= haversine.haversine(storeAddress,userAddress)
        
       
    except:
        print('Exception detected. ZipCode was :- ',row['Zip'])
        distance=-1
        invalidZipCount=invalidZipCount+1
        
    return distance

In [20]:

csvFile['Distance']=csvFile.apply (lambda row: distanceFromStore (row),axis=1)
print (invalidZipCount)

Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  107056
Exception detected. ZipCode was :-  1070310
Exception detected. ZipCode was :-  NY
Exception detected. ZipCode was :-  107033
Exception detected. ZipCode was :-  30088
Exception detected. ZipCode was :-  703
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  110000103
Exception detected. ZipCode was :-  10322
Exception detected. ZipCode was :-  10700
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  9146533365
Exception detected. ZipCode was :-  1701
Exception detected. ZipCode was :-  1701
Exception detected. ZipCode was :-  1003
Exception detected. ZipCode was :-  703
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  10771
Exception detected. ZipCode was :-  1070
Exception detected. ZipCode was :-  703
Exception detected. ZipCode was :-  6466849669
Exception detected. ZipCode was :-  120703
Exception detected. ZipCode was :-  107036
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  1
Exception detected. ZipCode was :-  701
Exception detected. ZipCode was :-  1003
Exception detected. ZipCode was :-  107019149635470
Exception detected. ZipCode was :-  1703
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  NY
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  107085
Exception detected. ZipCode was :-  99
Exception detected. ZipCode was :-  1
Exception detected. ZipCode was :-  1
Exception detected. ZipCode was :-  1
Exception detected. ZipCode was :-  1
Exception detected. ZipCode was :-  UNKNOW
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  1010701
Exception detected. ZipCode was :-  2
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  UNKNOW
Exception detected. ZipCode was :-  15498
Exception detected. ZipCode was :-  8750
Exception detected. ZipCode was :-  107201
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  107056
Exception detected. ZipCode was :-  1070310
Exception detected. ZipCode was :-  NY
Exception detected. ZipCode was :-  00000
Exception detected. ZipCode was :-  110000103
Exception detected. ZipCode was :-  16607
Exception detected. ZipCode was :-  9146533365
Exception detected. ZipCode was :-  1701
Exception detected. ZipCode was :-  1003
Exception detected. ZipCode was :-  00000
Exception detected. ZipCode was :-  1073
Exception detected. ZipCode was :-  10771
Exception detected. ZipCode was :-  1070
Exception detected. ZipCode was :-  0703
Exception detected. ZipCode was :-  1070
Exception detected. ZipCode was :-  120703
Exception detected. ZipCode was :-  10793
Exception detected. ZipCode was :-  00000
Exception detected. ZipCode was :-  0
Exception detected. ZipCode was :-  00000
Exception detected. ZipCode was :-  107063
Exception detected. ZipCode was :-  99
Exception detected. ZipCode was :-  1
Exception detected. ZipCode was :-  000000
Exception detected. ZipCode was :-  1010701
Exception detected. ZipCode was :-  UNKNOW
Exception detected. ZipCode was :-  00000
Exception detected. ZipCode was :-  UNKNOW
Exception detected. ZipCode was :-  UNKNNOW
Exception detected. ZipCode was :-  107021
Exception detected. ZipCode was :-  UNKNOW
Exception detected. ZipCode was :-  UNKNOW
Exception detected. ZipCode was :-  420416769177
Exception detected. ZipCode was :-  10571
Exception detected. ZipCode was :-  00000
92